openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'realmeet'
  description: Buy or rent spacecrafts

paths:
  /rooms:
    get:
      summary: Return rooms
      operationId: listRooms
      tags:
        - room
      parameters:
        - name: id
          in: query
          description: The unique identifier of the room
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Room'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          format: int32
          type: integer
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: []