# ========================================
# = Spring
# ========================================
spring:
  datasource:
    url: jdbc:mysql://realmeet-db.........:3306/realmeet?serverTimeZone=UTC&useSSL=false
    username: admin
